export {default as About} from './About'
export {default as Projects} from './Projects'
export {default as Skills} from './Skills'
export {default as Contact} from './Contact'
export {default as Fof} from './Fof'
export {default as Shutter} from './Shutter'
export {default as Call} from './Call'